CREATE DATABASE IF NOT EXISTS ${MYSQL_DB_NAME};

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DB_NAME}.* TO '${MYSQL_USER}'@'%';

INSERT IGNORE INTO weather_station (host, port, path, protocol, location) VALUES ('192.168.0.137', 80, "/", "http", "balcony");